### ISSUE TITLE
Employee Profile Information not showing 

### ISSUE THREAD

**Issue by SameerIslam** [UTDallasEPICS/ATC-Patient-Management-Frontend#62]
The birthday, phone number, and "other info" give an error when displaying on the EmployeeProfile page (likely due to a backend issue where the props for such are missing)

**Comment by Jonathan-Harty** [comment]
Please add screenshots for all errors occurred

**Comment by SameerIslam** [comment]
<img width="763" alt="image" src="https://user-images.githubusercontent.com/58448308/200709100-a313c84d-edc8-44e4-bb80-9e08f4ca6263.png">
<img width="769" alt="image" src="https://user-images.githubusercontent.com/58448308/200709196-5d134a6a-b5ee-4045-b340-8d5138ad999e.png">
<img width="774" alt="image" src="https://user-images.githubusercontent.com/58448308/200709258-6b2332d6-7f6b-4c72-85aa-335355816049.png">
